version: '3.4'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reviewservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - 5432:5432

  reviewservice:
    image: ${DOCKER_REGISTRY-}reviewservice
    build:
      context: ./ReviewService
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_HOST="${POSTGRES_HOST}"
      - POSTGRES_PORT="${POSTGRES_PORT}"
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - SERVICEBUS_CONNECTION_STRING="${SERVICEBUS_CONNECTION_STRING}"
      - ConnectionStrings__DefaultConnection="Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      - postgresql
    ports:
      - "5269:5269"

volumes:
  postgres-data:
    driver: local
