name: Build, Test, SonarCloud Analysis, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, analyze and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history for SonarCloud analysis

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x  # Use the specified .NET version

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory TestResults
          reportgenerator -reports:TestResults/**/*.xml -targetdir:TestResults/CoverageReport -reporttypes:HtmlInline_AzurePipelines;Cobertura

      - name: Begin SonarCloud analysis
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:"frederikhendrix_reviewservice" \
            /o:"frederikhendrix" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="TestResults/CoverageReport/coverage.cobertura.xml"

      - name: End SonarCloud analysis
        run: |
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # New steps for building and pushing Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ReviewService
          file: ./ReviewService/ReviewService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reviewservice-backend:latest
