# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      # Restore dependencies in the specific project directory
      - name: Restore dependencies
        run: dotnet restore ./ReviewService/ReviewService/ReviewService.csproj

      # Build the project in the specific directory
      - name: Build
        run: dotnet build ./ReviewService/ReviewService/ReviewService.csproj --no-restore

      # Test command needs to point to the correct test project path
      - name: Test
        run: dotnet test ./ReviewServiceTest/ReviewServiceTest.csproj --no-build --verbosity normal
